#!/bin/sh

for keyname in release-keys platform shared media verify
do
  echo "" | $ANDROID_BUILD_TOP/development/tools/make_key $keyname '/C=KR/L=Guri/O=ganachoco/OU=ganachoco/CN=ganachoco/emailAddress=ganadist@gmail.com'
done

for F in release-keys*
do
  ln -sf $F ${F/release-keys/testkey}
done
